front:
  build: .
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor
    - ./logs:/var/log/nginx/
    - ./logs:/var/log/php-fpm/

mysql:
  image: percona:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./sql:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: lbmg

redis:
  image: redis
  ports:
    - "6379:6379"
